[build]
  publish = "."

[[redirects]]
  from = "/admin/add-car"
  to = "/admin/car-list.html"
  status = 302
  force = true
  conditions = {Success = true}

# Fallback to handle any errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false